### ISSUE TITLE
MoLPC colab error 

### ISSUE THREAD

**Issue by JavBurgoa** [patrickbryant1/MoLPC#4]
Hi,

When running the test case works fine, but when trying to input our own sequence we get a `FileNotFound` error. However we don't think this is due to the naming of our input files. The file we are trying to run is in `/content/MSA_2.a3m`.

I attach some pictures with the variables inputted, and the error. 

**Variables inputted**
![Variables](https://user-images.githubusercontent.com/65179875/196631499-596c6293-c069-4f4c-a98b-d4f4790c74ce.png)

**Error**
![Error](https://user-images.githubusercontent.com/65179875/196631724-09bd16ed-dfa9-4c62-b54d-4be2621ce7ab.png)

Thank you in advance

**Comment by patrickbryant1** [comment]
Hi, It seems that the ID is missing. I am not sure why this is. Try renaming MSA1 to MSA_1.a3m.

**Comment by JavBurgoa** [comment]
Hi again,

Thank you for the suggestion. One of my colleagues tried and she found this:

=========================
If I play around with the ID of the run, then I get an error in step 1 of the pipeline `([Errno 2] No such file or directory: '/content/MSA1_1.a3m')`. 

I tried different combinations of IDs, and it lets me through to step 2 if I use ID: MSA 

However, in step 2 it blocks me again with the same error as before:  `[Errno 2] No such file or directory: '/content/gdrive/MyDrive/_1-2-3_paired.a3m'`


Different IDs tried, error in step 1


1. As Bryant suggested -> ID: MSA_1.a3m

`FileNotFoundError: [Errno 2] No such file or directory: '/content/MSA_1.a3m_1.a3m'`


3. ID: MSA1 (as yesterday)

`FileNotFoundError: [Errno 2] No such file or directory: '/content/MSA1_1.a3m'`


4. ID: Cucumber

`FileNotFoundError: [Errno 2] No such file or directory: '/content/Cucumber_1.a3m'`


5. No ID at all (blank field)

[Errno 2] No such file or directory: '/content/_1.a3m'

======================

So, apparently it cannot find the file in /content/ even though it has been uploaded there. Do you have any idea of why can this be?

Thank you in advance

**Comment by patrickbryant1** [comment]
Hi, I am sorry that the naming is not more clear. The problem seems to be that the naming is not exact, which is required. Let's say you fill in ID=MSA. If you want to name your different MSAs ID_1,..,ID_N then you have to follow this exact convention. This means that the first MSA should be named: MSA_1 and not MSA_1.a3m. As you can see, the script can't find the file because it assumes the ending '.a3m' meaning that it looks for MSA_1.a3m_1.a3m' and not MSA_1.a3m. If you change to simply MSA_1 - it should work.

I am referring to this error:
FileNotFoundError: [Errno 2] No such file or directory: '/content/MSA_1.a3m_1.a3m'
